### ISSUE TITLE
device partition is not deleted after volume deletion

### ISSUE THREAD

**Issue by w3aman** [openebs-archive/device-localpv#21]
- I created 5 volumes on single node and single disk `/dev/sdc`. 5 partitions were created `/dev/sdc2 ...to /dev/sdc6`.
when i deleted these 5 volumes at a time, i see that all 5 volumes has been deleted but device partition` /dev/sd2` is still present on the node.

- it doesn't happen everytime, but hitting this issue very frequently.

Looks like when multiple deletion request occurs at a time, some partitions are skipped from deletion.

```
$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk 
loop0    7:0    0 55.5M  1 loop /snap/core18/1988
loop1    7:1    0   51M  1 loop /snap/snap-store/518
loop2    7:2    0 64.8M  1 loop /snap/gtk-common-themes/1514
loop3    7:3    0 55.5M  1 loop /snap/core18/1997
loop4    7:4    0  219M  1 loop /snap/gnome-3-34-1804/66
loop5    7:5    0 65.1M  1 loop /snap/gtk-common-themes/1515
loop6    7:6    0 32.3M  1 loop /snap/snapd/11402
loop7    7:7    0 32.3M  1 loop /snap/snapd/11588
sda      8:0    0  100G  0 disk 
├─sda1   8:1    0  512M  0 part /boot/efi
├─sda2   8:2    0    1K  0 part 
└─sda5   8:5    0 99.5G  0 part /
sdb      8:16   0   50G  0 disk 
sdc      8:32   0   50G  0 disk 
├─sdc1   8:33   0    9M  0 part 
└─sdc2   8:34   0    1G  0 part 
```
We can see here that no volume is present in cluser.
```
$ k get pvc -A
No resources found
$ k get pv
No resources found
$ k get devicevol -A
No resources found
```
but on node, we can see
```
$ sudo parted /dev/sdc unit b print --script
Model: VMware Virtual disk (scsi)
Disk /dev/sdc: 53687091200B
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start      End          Size         File system  Name                                  Flags
 1      1048576B   10485759B    9437184B                  e2e-device
 2      10485760B  1084227583B  1073741824B               4c1d2a6d-6984-420d-8cfa-f028613e12fd
```
When i tried deleting partition manually it successfully gets deleted.
```
$ sudo parted /dev/sdc rm 2 --script
$ lsblk

sdb      8:16   0   50G  0 disk 
sdc      8:32   0   50G  0 disk 
└─sdc1   8:33   0    9M  0 part 
sdd      8:48   0   50G  0 disk 
```

**How to Reproduce issue**
- Create multiple volumes say 5, and try to delete them all at a time like `kubectl delete pvc --all`, and check the disk partition on nodes. You may not hit it every-time but hopefully will hit the issue in 2-3 times.

**Logs**
[Device-controller-logs.txt](https://github.com/openebs/device-localpv/files/6740373/Device-controller-logs.txt)
[device-node-agent-logs.txt](https://github.com/openebs/device-localpv/files/6740374/device-node-agent-logs.txt)

**Comment by iyashu** [comment]
I think we need to understand if parted cmd invocation for a single disk is concurrent safe or not. It was always questionable in my mind.

@w3aman can you change the threadiness to 1 as mentioned below and see if you are still able to reproduce the issue.
https://github.com/openebs/device-localpv/blob/8ae6bc14d1d357bca633c52c46eeaf88af3f67be/pkg/mgmt/volume/start.go#L89

**Comment by akhilerm** [comment]
@iyashu Tried with `threadiness=1`, and I didn't hit the issue. I think your suspicion was correct. `parted` is having issues with multithread.

**Comment by akhilerm** [comment]
@iyashu  Also, this issue is found only when the volume binding mode is set to Immediate.
