### ISSUE TITLE
Fix Error Handling

### ISSUE THREAD

**Issue by iyashu** [openebs-archive/device-localpv#29]
Hi folks, i see one place (need to look into it exhaustively) where the error handling is not done correctly. Can anyone pick it up?

Returning nil error from `findBestPart` & ` GetFreeCapacity` function results in invoking following parted command - 
```
device-util.go:312] Device LocalPV: could not Run command [parted /dev/ mkpart c44356ce-0fe9-472b-9a44-64385d8e6c1e 0MiB 9060352MiB --script]
```
https://github.com/openebs/device-localpv/blob/5212adbb17b9089426b00ba1f5da6b1366f2214b/pkg/device/device-util.go#L223-L246

**Comment by pawanpraka1** [comment]
@iyashu Not able to get the issue. Could you elaborate the problem.

**Comment by iyashu** [comment]
@pawanpraka1 as you see in above function the error returned at line 246 will always be nil. If there is no enough space exists in the disk to provision a given volume, the plugin will unnecessarily invoke parted mkpart with empty disk name as mentioned above. I think we need to return error from `findBestPart` (GetFreeCapacity) method if there is no space available to accommodate the volume.

**Comment by akhilerm** [comment]
@iyashu for `findBestPart` it makes sense to return the error. But for `GetFreeCapacity`, having no free space is not an error right? We just return available size as 0.

**Comment by iyashu** [comment]
@akhilerm just now checked the usage of `GetFreeCapacity` func. You are right, we just need to return maximum size available for a disk (0 if no free parts are there). Also, let's remove the log line `klog.Errorln("Device LocalPV: Free space for partition is not found")` from `GetFreeCapacity` func as well since it's confusing and its valid situation that one can have i.e zero free space.
